name: Run Python Script and Commit File
on: 
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-lastest

        steps: 
            - name: Checkout repository
             uses: actions/checkout@v2

            - name: Checkout repository
            uses: actions/checkout@v2